export const LOAD_INGREDIENTS = 'LOAD_INGREDIENTS';
export const SHOW_BURGER_INGREDIENTS = 'SHOW_BURGER_INGREDIENTS';
export const SHOW_INGREDIENT = 'SHOW_INGREDIENT';
export const HIDE_INGREDIENT = 'HIDE_INGREDIENT';
export const SUBMIT_ORDER = 'SUBMIT_ORDER';
export const SHOW_ORDER_NUMBER = 'SHOW_ORDER_NUMBER';
export const HIDE_ORDER_NUMBER = 'HIDE_ORDER_NUMBER';